### ISSUE TITLE
Does not highlight quoted and single-letter keys

### ISSUE THREAD

**Issue by chillum** [dryman/toml-mode.el#6]
In TOML this is valid example from the readme:

``` toml
[dog."tater.man"]
type = "pug"
```

toml-mode highlighting is broken with that.

And one more related thing: for some case toml-mode does not recognize one-letter-keys, although, as for TOML docs this is valid:

``` toml
[a]
b = "c"
```
